[tool.black]
line-length = 120
target-version = ["py310"]
exclude = '/(\.git|\.idea|\.vscode|\__pycache__)/'

[tool.isort]
profile = "black"
py_version = 310

[tool.flake8]
exclude = ".git,__pycache__"
select = "C,E,F,W,B,B950"
ignore = "E501, W503"
# see https://lintlyci.github.io/Flake8Rules/

[tool.pycln]
all = true

[tool.mypy]
python_version = "3.10"
mypy_path = ["src", "tests"]
